### PR TITLE
annotate $uibModal for ng-strict-di

### PR DESCRIPTION
**Pull request by bastienmoulia**

### CODE REVIEW

**Comment by dbtek** [comment]
Hi @bastienmoulia,

Thanks for the PR!. The problem reported in #30 was about auto-annotation which should be done in grunt tasks. Here I was using ngmin, which is deprecated by ng-annotate. Also there was a config problem I guess. So replacing it with ng-annotate provides auto annotation in dist files; so we don't have to write annotations on src files.

**Comment by dbtek** [comment]
Ps. problem solved on v1.3.1.

**Comment by bastienmoulia** [comment]
The ng-annotate is great for minification files, but I also need it in non-minified files.
By exemple, with Yeoman, my task runner can lanch the website in 2 mode:
* In development  the normal JS files are used
* In production the files are minified and merged in one file.
So I have an error in development becaude of it.

**Comment by dbtek** [comment]
There is non minified file under dist. How do you use ng-aside, without a package manager?

**Comment by dbtek** [comment]
Besides ng-annotate is not for minification.

**Comment by bastienmoulia** [comment]
Yes, with bower, so the non minified files is used automatically. I can force grunt to use the minified one, but other people could have this bug.

**Pull request closed without merging**
