### PR TITLE
Add commonjs support and metadata to package.json

### LINKED ISSUE #27: Publish to npm
Hi, any chance you could publish this module to npm?

It should be as simple as adding this to your package.json:
```
...
browser: "dist/js/angular-aside.js",
style: "dist/css/angular-aside.css",
...
```

and then running `npm publish`.

Thanks!

### PR DESCRIPTION
**Pull request by mattlewis92**
Closes #27

### CODE REVIEW

**Comment by dbtek** [comment]
Oh, that was fast! Thanks @mattlewis92.

I don't know about the `style` field but, `index.js` should be in the `main` field value, shouldn't it?

**Comment by dbtek** [comment]
Actually as it's name is 'index.js' there is no necessity for `main` field. `browser` field is for bundlers only I guess.

**Comment by mattlewis92** [comment]
Yup `browser` is a non standardised field but used by the main module bundlers (i.e. webpack + browserify) to indicate that this is the entry point for a browser module.

**Comment by dbtek** [comment]
It's ok then. Adding `.npmignore` file is the only thing to do before merge.
Contents would be:
```
src
test
Gruntfile.js
bower.json
karma.conf.js
.jshintrc
```

**Comment by mattlewis92** [comment]
Good shout, I've added that now :)

**Comment by dbtek** [comment]
Thanks  a lot @mattlewis92. Appreciated :relaxed:

**Comment by mattlewis92** [comment]
NP, happy to help, thanks for getting back to me so quickly! :smile:

**Pull request merged**
